/* -------- This file has been automatically generated by configure ---------
   Note: Any changes in it will be lost when you run configure again. */

/* Protect against multiple inclusion */
#ifndef MPLAYER_CONFIG_H
#define MPLAYER_CONFIG_H

#define CONFIGURATION "--with-twiizers"

#ifndef CODECS2HTML
#include "osdep/plat_gekko.h"
#endif

/* make sure we never get lavformat's poll() emulation, the results are
   horrible if the X libs try to actually use it, see MPlayer-users
   Message-ID: <45D49541.8060101@infernix.net>
   Date: Thu, 15 Feb 2007 18:15:45 +0100
   Subject: [MPlayer-users] Crash with backtrace when playing back demuxed...
*/
#define HAVE_SYS_POLL_H 1

/* yes, we have inttypes.h */
#define HAVE_INTTYPES_H 1

/* int_fastXY_t emulation */


/* libdvdcss */
#define HAVE_ERRNO_H 1

/* libdvdcss + libdvdread */
#define HAVE_LIMITS_H 1

/* libdvdcss + libfaad2 */
#define HAVE_UNISTD_H 1

/* libfaad2 + libdvdread */
#define STDC_HEADERS 1

/* libfaad2 */
#define HAVE_MEMCPY 1
#define HAVE_STRCHR 1

/* libdvdread */
#define HAVE_UINTPTR_T 1

/* name of messages charset */
#define MSG_CHARSET "UTF-8"

/* Runtime CPU detection */
#undef RUNTIME_CPUDETECT

/* Dynamic a/v plugins */
#undef CONFIG_DYNAMIC_PLUGINS

/* "restrict" keyword */
#define restrict __restrict

/* __builtin_expect branch prediction hint */
#define HAVE_BUILTIN_EXPECT 1
#ifdef HAVE_BUILTIN_EXPECT
#define likely(x) __builtin_expect ((x) != 0, 1)
#define unlikely(x) __builtin_expect ((x) != 0, 0)
#else
#define likely(x) (x)
#define unlikely(x) (x)
#endif

/* attribute(used) as needed by some compilers */
#if (__GNUC__ * 100 + __GNUC_MINOR__ >= 300)
# define attribute_used __attribute__((used))
#else
# define attribute_used
#endif

/* extern symbol prefix */
#define EXTERN_PREFIX ""

/* compiler support for named assembler arguments */
#define NAMED_ASM_ARGS 1

/* enable/disable SIGHANDLER */
#undef CONFIG_SIGHANDLER

/* enable/disable automatic gdb attach on crash, requires SIGHANDLER */
#undef CONFIG_CRASH_DEBUG

/* Toggles debugging informations */
#undef MP_DEBUG

/* Indicates that libcdio is available for VCD and CD-DA playback */
#undef CONFIG_LIBCDIO

/* Indicates that Ogle's libdvdread is available for DVD playback */
#define CONFIG_DVDREAD 1

/* Indicates that dvdread is internal */


/* Additional options for libdvdread/libdvdcss */
#undef DVD_STRUCT_IN_DVD_H
#undef DVD_STRUCT_IN_LINUX_CDROM_H
#undef DVD_STRUCT_IN_SYS_CDIO_H
#undef DVD_STRUCT_IN_SYS_DVDIO_H








/* Common data directory (for fonts, etc) */
#define MPLAYER_DATADIR "sd:/apps/mplayer_ce"
#define MPLAYER_CONFDIR "sd:/apps/mplayer_ce"
#define MPLAYER_LIBDIR "sd:/apps/mplayer_ce"

/* Define this to compile stream-caching support, it can be enabled via
   -cache <kilobytes> */
#define CONFIG_STREAM_CACHE 1

/* Define if you are using Xvid library */
#undef CONFIG_XVID4

/* Define if you are using the X.264 library */
#undef CONFIG_X264

/* Define if you are using libnut */
#undef CONFIG_LIBNUT

/* Define to include support for libdv-0.9.5 */
#undef CONFIG_LIBDV095

/* Indicates if libmp3lame is available
   Note: for mencoder */




/* Undefine this if you do not want to select mono audio (left or right)
   with a stereo MPEG layer 2/3 audio stream. The command line option
   -stereo has three possible values (0 for stereo, 1 for left-only, 2 for
   right-only), with 0 being the default.
   */
#define CONFIG_FAKE_MONO 1

/* Undefine this if your sound card driver has no working select().
   If you have kernel Oops, player hangups, or just no audio, you should
   try to recompile MPlayer with this option disabled! */
#define HAVE_AUDIO_SELECT 1

/* define this to use iconv(3) function to codepage conversions */
#undef CONFIG_ICONV

/* define this to use nl_langinfo function */
#define HAVE_LANGINFO 1

/* define this to use RTC (/dev/rtc) for video timers */
#undef HAVE_RTC

/* set up max. outburst. use 65536 for ALSA 0.5, for others 16384 is enough */
#define MAX_OUTBURST 65536

/* set up audio OUTBURST. Do not change this! */
#define OUTBURST 512

/* Define this if your system has the header file for the OSS sound interface */
#undef HAVE_SYS_SOUNDCARD_H

/* Define this if your system has the header file for the OSS sound interface
 * in /usr/include */
#undef HAVE_SOUNDCARD_H

/* Define this if your system has the sysinfo header */
#undef HAVE_SYS_SYSINFO_H

/* Define this if your system has the "malloc.h" header file */
#define HAVE_MALLOC_H 1

/* memalign is mapped to malloc if unsupported */
#define HAVE_MEMALIGN 1



/* assembler handling of .align */
#define ASMALIGN(ZEROBITS) ".align " #ZEROBITS "\n\t"

/* Define this if your system has the "alloca.h" header file */
#define HAVE_ALLOCA_H 1

/* Define this if your system has the "byteswap.h" header file */
#undef HAVE_BYTESWAP_H

/* Define this if your system has the "sys/mman.h" header file */
#undef HAVE_SYS_MMAN_H
#define MAP_FAILED ((void *) -1)

/* Define this if you have the elf dynamic linker -ldl library */
#undef HAVE_LIBDL

/* Define this if you have the kstat kernel statistics library */
#undef HAVE_LIBKSTAT

/* Define this if you have zlib */
#undef CONFIG_ZLIB

/* Define this if you have shm support */
#undef HAVE_SHM

/* Define this if your system has strsep */
#define HAVE_STRSEP 1

/* Define this if your system has vsscanf */
#define HAVE_VSSCANF 1

/* Define this if your system has swab */
#define HAVE_SWAB 1

/* Define this if your system has posix select */
#undef HAVE_POSIX_SELECT

/* Define this if your system has gettimeofday */
#define HAVE_GETTIMEOFDAY 1

/* Define this if your system has glob */
#undef HAVE_GLOB

/* Define this if your system has setenv */
#define HAVE_SETENV 1
#ifndef HAVE_SETENV
int setenv(const char *name, const char *val, int overwrite);
#endif

/* Define this if your system has sysi86 */



/* Define this if your system has pthreads */
#undef HAVE_PTHREADS

/* LIRC (remote control, see www.lirc.org) support: */
#undef CONFIG_LIRC

/* Apple Remote (remote control, see http://docs.info.apple.com/article.html?artnum=302504) support: */


/* Apple IR Remote (Linux remote control driver) */


/* Support for maemo (http://www.maemo.org) */


/*
 * LIRCCD (LIRC client daemon)
 * See http://www.dolda2000.cjb.net/~fredrik/lirccd/
 */
#undef CONFIG_LIRCC

/* DVD navigation support using libdvdnav */
#define CONFIG_DVDNAV 1

/* Define this to enable MPEG 1/2 image postprocessing (requires a FAST CPU!) */
#define MPEG12_POSTPROC 1

/* maximum alignment used by libmpeg2 */
#define ATTRIBUTE_ALIGNED_MAX 16

/* Win32 DLL support */
#undef CONFIG_WIN32DLL
#define WIN32_PATH ""

/* Mac OS X specific features */







/* Build our Win32-loader */
#undef WIN32_LOADER

/* FFmpeg */
/* Define this to enable image postprocessing in libavcodec (requires a FAST CPU!) */
#define CONFIG_LIBPOSTPROC 1
#define CONFIG_LIBPOSTPROC_A 1
#undef CONFIG_LIBPOSTPROC_SO

/* Define this if you enabled thread support for libavcodec */
#undef HAVE_THREADS
#ifdef HAVE_THREADS
#define ENABLE_THREADS 1
#else
#define ENABLE_THREADS 0
#endif

/* ffmpeg's libavcodec support (requires libavcodec source) */
#define CONFIG_LIBAVCODEC 1
#define CONFIG_LIBAVCODEC_A 1
#undef CONFIG_LIBAVCODEC_SO
#define CONFIG_MPEGAUDIO_HP 1

/* ffmpeg's libavformat support (requires libavformat source) */
#define CONFIG_LIBAVFORMAT 1
#define CONFIG_LIBAVFORMAT_A 1
#undef CONFIG_LIBAVFORMAT_SO

#define CONFIG_LIBAVUTIL 1
#define CONFIG_LIBAVUTIL_A 1
#undef CONFIG_LIBAVUTIL_SO

/* Use libavcodec's decoders */
#define CONFIG_DECODERS 1
#define ENABLE_DECODERS 1
/* Use libavcodec's encoders */
#define CONFIG_ENCODERS 1
#define ENABLE_ENCODERS 1

/* Use libavformat's demuxers */
#define CONFIG_DEMUXERS 1
#define ENABLE_DEMUXERS 1
/* Use libavformat's muxers */


/* Use these registers in FFmpeg x86 inline asm. No proper detection yet. */
#define HAVE_EBX_AVAILABLE 1
#ifndef MP_DEBUG
#define HAVE_EBP_AVAILABLE 1
#endif

#define CONFIG_GPL 1
#define ENABLE_SMALL 0
#define ENABLE_GRAY 0

/* Use AMR codecs from libavcodec. */

#undef CONFIG_LIBAMR_NB
#undef CONFIG_LIBAMR_WB

/* Use specific parts from FFmpeg. */
#define CONFIG_AASC_DECODER 1
#define ENABLE_AASC_DECODER 1
#define CONFIG_AMV_DECODER 1
#define ENABLE_AMV_DECODER 1
#define CONFIG_ASV1_DECODER 1
#define ENABLE_ASV1_DECODER 1
#define CONFIG_ASV2_DECODER 1
#define ENABLE_ASV2_DECODER 1
#define CONFIG_AVS_DECODER 1
#define ENABLE_AVS_DECODER 1
#define CONFIG_BETHSOFTVID_DECODER 1
#define ENABLE_BETHSOFTVID_DECODER 1
#define CONFIG_BFI_DECODER 1
#define ENABLE_BFI_DECODER 1
#define CONFIG_BMP_DECODER 1
#define ENABLE_BMP_DECODER 1
#define CONFIG_C93_DECODER 1
#define ENABLE_C93_DECODER 1
#define CONFIG_CAVS_DECODER 1
#define ENABLE_CAVS_DECODER 1
#define CONFIG_CINEPAK_DECODER 1
#define ENABLE_CINEPAK_DECODER 1
#define CONFIG_CLJR_DECODER 1
#define ENABLE_CLJR_DECODER 1
#define CONFIG_CSCD_DECODER 1
#define ENABLE_CSCD_DECODER 1
#define CONFIG_CYUV_DECODER 1
#define ENABLE_CYUV_DECODER 1
#define CONFIG_DNXHD_DECODER 1
#define ENABLE_DNXHD_DECODER 1
#define CONFIG_DSICINVIDEO_DECODER 1
#define ENABLE_DSICINVIDEO_DECODER 1
#define CONFIG_DVVIDEO_DECODER 1
#define ENABLE_DVVIDEO_DECODER 1
#define ENABLE_DXA_DECODER 0
#define CONFIG_EACMV_DECODER 1
#define ENABLE_EACMV_DECODER 1
#define CONFIG_EATGV_DECODER 1
#define ENABLE_EATGV_DECODER 1
#define CONFIG_EIGHTBPS_DECODER 1
#define ENABLE_EIGHTBPS_DECODER 1
#define CONFIG_EIGHTSVX_EXP_DECODER 1
#define ENABLE_EIGHTSVX_EXP_DECODER 1
#define CONFIG_EIGHTSVX_FIB_DECODER 1
#define ENABLE_EIGHTSVX_FIB_DECODER 1
#define CONFIG_ESCAPE124_DECODER 1
#define ENABLE_ESCAPE124_DECODER 1
#define CONFIG_FFV1_DECODER 1
#define ENABLE_FFV1_DECODER 1
#define CONFIG_FFVHUFF_DECODER 1
#define ENABLE_FFVHUFF_DECODER 1
#define ENABLE_FLASHSV_DECODER 0
#define CONFIG_FLIC_DECODER 1
#define ENABLE_FLIC_DECODER 1
#define CONFIG_FLV_DECODER 1
#define ENABLE_FLV_DECODER 1
#define CONFIG_FOURXM_DECODER 1
#define ENABLE_FOURXM_DECODER 1
#define CONFIG_FRAPS_DECODER 1
#define ENABLE_FRAPS_DECODER 1
#define CONFIG_GIF_DECODER 1
#define ENABLE_GIF_DECODER 1
#define CONFIG_H261_DECODER 1
#define ENABLE_H261_DECODER 1
#define CONFIG_H263_DECODER 1
#define ENABLE_H263_DECODER 1
#define CONFIG_H263I_DECODER 1
#define ENABLE_H263I_DECODER 1
#define CONFIG_H264_DECODER 1
#define ENABLE_H264_DECODER 1
#define CONFIG_HUFFYUV_DECODER 1
#define ENABLE_HUFFYUV_DECODER 1
#define CONFIG_IDCIN_DECODER 1
#define ENABLE_IDCIN_DECODER 1
#define CONFIG_INDEO2_DECODER 1
#define ENABLE_INDEO2_DECODER 1
#define CONFIG_INDEO3_DECODER 1
#define ENABLE_INDEO3_DECODER 1
#define CONFIG_INTERPLAY_VIDEO_DECODER 1
#define ENABLE_INTERPLAY_VIDEO_DECODER 1
#define CONFIG_JPEGLS_DECODER 1
#define ENABLE_JPEGLS_DECODER 1
#define CONFIG_KMVC_DECODER 1
#define ENABLE_KMVC_DECODER 1
#define CONFIG_LOCO_DECODER 1
#define ENABLE_LOCO_DECODER 1
#define CONFIG_MDEC_DECODER 1
#define ENABLE_MDEC_DECODER 1
#define CONFIG_MIMIC_DECODER 1
#define ENABLE_MIMIC_DECODER 1
#define CONFIG_MJPEG_DECODER 1
#define ENABLE_MJPEG_DECODER 1
#define CONFIG_MJPEGB_DECODER 1
#define ENABLE_MJPEGB_DECODER 1
#define CONFIG_MMVIDEO_DECODER 1
#define ENABLE_MMVIDEO_DECODER 1
#define CONFIG_MOTIONPIXELS_DECODER 1
#define ENABLE_MOTIONPIXELS_DECODER 1
#define ENABLE_MPEG_XVMC_DECODER 0
#define CONFIG_MPEG1VIDEO_DECODER 1
#define ENABLE_MPEG1VIDEO_DECODER 1
#define CONFIG_MPEG2VIDEO_DECODER 1
#define ENABLE_MPEG2VIDEO_DECODER 1
#define CONFIG_MPEG4_DECODER 1
#define ENABLE_MPEG4_DECODER 1
#define CONFIG_MPEGVIDEO_DECODER 1
#define ENABLE_MPEGVIDEO_DECODER 1
#define CONFIG_MSMPEG4V1_DECODER 1
#define ENABLE_MSMPEG4V1_DECODER 1
#define CONFIG_MSMPEG4V2_DECODER 1
#define ENABLE_MSMPEG4V2_DECODER 1
#define CONFIG_MSMPEG4V3_DECODER 1
#define ENABLE_MSMPEG4V3_DECODER 1
#define CONFIG_MSRLE_DECODER 1
#define ENABLE_MSRLE_DECODER 1
#define CONFIG_MSVIDEO1_DECODER 1
#define ENABLE_MSVIDEO1_DECODER 1
#define CONFIG_MSZH_DECODER 1
#define ENABLE_MSZH_DECODER 1
#define CONFIG_NUV_DECODER 1
#define ENABLE_NUV_DECODER 1
#define CONFIG_PCX_DECODER 1
#define ENABLE_PCX_DECODER 1
#define ENABLE_PNG_DECODER 0
#define CONFIG_PTX_DECODER 1
#define ENABLE_PTX_DECODER 1
#define CONFIG_QDRAW_DECODER 1
#define ENABLE_QDRAW_DECODER 1
#define CONFIG_QPEG_DECODER 1
#define ENABLE_QPEG_DECODER 1
#define CONFIG_QTRLE_DECODER 1
#define ENABLE_QTRLE_DECODER 1
#define CONFIG_RAWVIDEO_DECODER 1
#define ENABLE_RAWVIDEO_DECODER 1
#define CONFIG_RL2_DECODER 1
#define ENABLE_RL2_DECODER 1
#define CONFIG_ROQ_DECODER 1
#define ENABLE_ROQ_DECODER 1
#define CONFIG_RPZA_DECODER 1
#define ENABLE_RPZA_DECODER 1
#define CONFIG_RV10_DECODER 1
#define ENABLE_RV10_DECODER 1
#define CONFIG_RV20_DECODER 1
#define ENABLE_RV20_DECODER 1
#define CONFIG_SGI_DECODER 1
#define ENABLE_SGI_DECODER 1
#define CONFIG_SMACKER_DECODER 1
#define ENABLE_SMACKER_DECODER 1
#define CONFIG_SMC_DECODER 1
#define ENABLE_SMC_DECODER 1
#define CONFIG_SNOW_DECODER 1
#define ENABLE_SNOW_DECODER 1
#define CONFIG_SP5X_DECODER 1
#define ENABLE_SP5X_DECODER 1
#define CONFIG_SUNRAST_DECODER 1
#define ENABLE_SUNRAST_DECODER 1
#define CONFIG_SVQ1_DECODER 1
#define ENABLE_SVQ1_DECODER 1
#define CONFIG_SVQ3_DECODER 1
#define ENABLE_SVQ3_DECODER 1
#define CONFIG_TARGA_DECODER 1
#define ENABLE_TARGA_DECODER 1
#define CONFIG_THEORA_DECODER 1
#define ENABLE_THEORA_DECODER 1
#define CONFIG_THP_DECODER 1
#define ENABLE_THP_DECODER 1
#define CONFIG_TIERTEXSEQVIDEO_DECODER 1
#define ENABLE_TIERTEXSEQVIDEO_DECODER 1
#define CONFIG_TIFF_DECODER 1
#define ENABLE_TIFF_DECODER 1
#define CONFIG_TRUEMOTION1_DECODER 1
#define ENABLE_TRUEMOTION1_DECODER 1
#define CONFIG_TRUEMOTION2_DECODER 1
#define ENABLE_TRUEMOTION2_DECODER 1
#define CONFIG_TSCC_DECODER 1
#define ENABLE_TSCC_DECODER 1
#define CONFIG_TXD_DECODER 1
#define ENABLE_TXD_DECODER 1
#define CONFIG_ULTI_DECODER 1
#define ENABLE_ULTI_DECODER 1
#define CONFIG_VB_DECODER 1
#define ENABLE_VB_DECODER 1
#define CONFIG_VC1_DECODER 1
#define ENABLE_VC1_DECODER 1
#define CONFIG_VCR1_DECODER 1
#define ENABLE_VCR1_DECODER 1
#define CONFIG_VMDVIDEO_DECODER 1
#define ENABLE_VMDVIDEO_DECODER 1
#define CONFIG_VMNC_DECODER 1
#define ENABLE_VMNC_DECODER 1
#define CONFIG_VP3_DECODER 1
#define ENABLE_VP3_DECODER 1
#define CONFIG_VP5_DECODER 1
#define ENABLE_VP5_DECODER 1
#define CONFIG_VP6_DECODER 1
#define ENABLE_VP6_DECODER 1
#define CONFIG_VP6A_DECODER 1
#define ENABLE_VP6A_DECODER 1
#define CONFIG_VP6F_DECODER 1
#define ENABLE_VP6F_DECODER 1
#define CONFIG_VQA_DECODER 1
#define ENABLE_VQA_DECODER 1
#define CONFIG_WMV1_DECODER 1
#define ENABLE_WMV1_DECODER 1
#define CONFIG_WMV2_DECODER 1
#define ENABLE_WMV2_DECODER 1
#define CONFIG_WMV3_DECODER 1
#define ENABLE_WMV3_DECODER 1
#define CONFIG_WNV1_DECODER 1
#define ENABLE_WNV1_DECODER 1
#define CONFIG_XAN_WC3_DECODER 1
#define ENABLE_XAN_WC3_DECODER 1
#define CONFIG_XL_DECODER 1
#define ENABLE_XL_DECODER 1
#define CONFIG_XSUB_DECODER 1
#define ENABLE_XSUB_DECODER 1
#define CONFIG_ZLIB_DECODER 1
#define ENABLE_ZLIB_DECODER 1
#define ENABLE_ZMBV_DECODER 0
#define CONFIG_AC3_DECODER 1
#define ENABLE_AC3_DECODER 1
#define CONFIG_ALAC_DECODER 1
#define ENABLE_ALAC_DECODER 1
#define CONFIG_APE_DECODER 1
#define ENABLE_APE_DECODER 1
#define CONFIG_ATRAC3_DECODER 1
#define ENABLE_ATRAC3_DECODER 1
#define CONFIG_COOK_DECODER 1
#define ENABLE_COOK_DECODER 1
#define CONFIG_DCA_DECODER 1
#define ENABLE_DCA_DECODER 1
#define CONFIG_DSICINAUDIO_DECODER 1
#define ENABLE_DSICINAUDIO_DECODER 1
#define CONFIG_FLAC_DECODER 1
#define ENABLE_FLAC_DECODER 1
#define CONFIG_IMC_DECODER 1
#define ENABLE_IMC_DECODER 1
#define CONFIG_MACE3_DECODER 1
#define ENABLE_MACE3_DECODER 1
#define CONFIG_MACE6_DECODER 1
#define ENABLE_MACE6_DECODER 1
#define CONFIG_MLP_DECODER 1
#define ENABLE_MLP_DECODER 1
#define CONFIG_MP2_DECODER 1
#define ENABLE_MP2_DECODER 1
#define CONFIG_MP3_DECODER 1
#define ENABLE_MP3_DECODER 1
#define CONFIG_MP3ADU_DECODER 1
#define ENABLE_MP3ADU_DECODER 1
#define CONFIG_MP3ON4_DECODER 1
#define ENABLE_MP3ON4_DECODER 1
#define CONFIG_MPC7_DECODER 1
#define ENABLE_MPC7_DECODER 1
#define CONFIG_MPC8_DECODER 1
#define ENABLE_MPC8_DECODER 1
#define CONFIG_NELLYMOSER_DECODER 1
#define ENABLE_NELLYMOSER_DECODER 1
#define CONFIG_QDM2_DECODER 1
#define ENABLE_QDM2_DECODER 1
#define CONFIG_RA_144_DECODER 1
#define ENABLE_RA_144_DECODER 1
#define CONFIG_RA_288_DECODER 1
#define ENABLE_RA_288_DECODER 1
#define CONFIG_SHORTEN_DECODER 1
#define ENABLE_SHORTEN_DECODER 1
#define CONFIG_SMACKAUD_DECODER 1
#define ENABLE_SMACKAUD_DECODER 1
#define CONFIG_SONIC_DECODER 1
#define ENABLE_SONIC_DECODER 1
#define CONFIG_TRUESPEECH_DECODER 1
#define ENABLE_TRUESPEECH_DECODER 1
#define CONFIG_TTA_DECODER 1
#define ENABLE_TTA_DECODER 1
#define CONFIG_VMDAUDIO_DECODER 1
#define ENABLE_VMDAUDIO_DECODER 1
#define CONFIG_VORBIS_DECODER 1
#define ENABLE_VORBIS_DECODER 1
#define CONFIG_WAVPACK_DECODER 1
#define ENABLE_WAVPACK_DECODER 1
#define CONFIG_WMAV1_DECODER 1
#define ENABLE_WMAV1_DECODER 1
#define CONFIG_WMAV2_DECODER 1
#define ENABLE_WMAV2_DECODER 1
#define CONFIG_WS_SND1_DECODER 1
#define ENABLE_WS_SND1_DECODER 1
#define CONFIG_PCM_ALAW_DECODER 1
#define ENABLE_PCM_ALAW_DECODER 1
#define CONFIG_PCM_DVD_DECODER 1
#define ENABLE_PCM_DVD_DECODER 1
#define CONFIG_PCM_F32BE_DECODER 1
#define ENABLE_PCM_F32BE_DECODER 1
#define CONFIG_PCM_MULAW_DECODER 1
#define ENABLE_PCM_MULAW_DECODER 1
#define CONFIG_PCM_S8_DECODER 1
#define ENABLE_PCM_S8_DECODER 1
#define CONFIG_PCM_S16BE_DECODER 1
#define ENABLE_PCM_S16BE_DECODER 1
#define CONFIG_PCM_S16LE_DECODER 1
#define ENABLE_PCM_S16LE_DECODER 1
#define CONFIG_PCM_S16LE_PLANAR_DECODER 1
#define ENABLE_PCM_S16LE_PLANAR_DECODER 1
#define CONFIG_PCM_S24BE_DECODER 1
#define ENABLE_PCM_S24BE_DECODER 1
#define CONFIG_PCM_S24DAUD_DECODER 1
#define ENABLE_PCM_S24DAUD_DECODER 1
#define CONFIG_PCM_S24LE_DECODER 1
#define ENABLE_PCM_S24LE_DECODER 1
#define CONFIG_PCM_S32BE_DECODER 1
#define ENABLE_PCM_S32BE_DECODER 1
#define CONFIG_PCM_S32LE_DECODER 1
#define ENABLE_PCM_S32LE_DECODER 1
#define CONFIG_PCM_U8_DECODER 1
#define ENABLE_PCM_U8_DECODER 1
#define CONFIG_PCM_U16BE_DECODER 1
#define ENABLE_PCM_U16BE_DECODER 1
#define CONFIG_PCM_U16LE_DECODER 1
#define ENABLE_PCM_U16LE_DECODER 1
#define CONFIG_PCM_U24BE_DECODER 1
#define ENABLE_PCM_U24BE_DECODER 1
#define CONFIG_PCM_U24LE_DECODER 1
#define ENABLE_PCM_U24LE_DECODER 1
#define CONFIG_PCM_U32BE_DECODER 1
#define ENABLE_PCM_U32BE_DECODER 1
#define CONFIG_PCM_U32LE_DECODER 1
#define ENABLE_PCM_U32LE_DECODER 1
#define CONFIG_PCM_ZORK_DECODER 1
#define ENABLE_PCM_ZORK_DECODER 1
#define CONFIG_INTERPLAY_DPCM_DECODER 1
#define ENABLE_INTERPLAY_DPCM_DECODER 1
#define CONFIG_ROQ_DPCM_DECODER 1
#define ENABLE_ROQ_DPCM_DECODER 1
#define CONFIG_SOL_DPCM_DECODER 1
#define ENABLE_SOL_DPCM_DECODER 1
#define CONFIG_XAN_DPCM_DECODER 1
#define ENABLE_XAN_DPCM_DECODER 1
#define CONFIG_ADPCM_4XM_DECODER 1
#define ENABLE_ADPCM_4XM_DECODER 1
#define CONFIG_ADPCM_ADX_DECODER 1
#define ENABLE_ADPCM_ADX_DECODER 1
#define CONFIG_ADPCM_CT_DECODER 1
#define ENABLE_ADPCM_CT_DECODER 1
#define CONFIG_ADPCM_EA_DECODER 1
#define ENABLE_ADPCM_EA_DECODER 1
#define CONFIG_ADPCM_EA_MAXIS_XA_DECODER 1
#define ENABLE_ADPCM_EA_MAXIS_XA_DECODER 1
#define CONFIG_ADPCM_EA_R1_DECODER 1
#define ENABLE_ADPCM_EA_R1_DECODER 1
#define CONFIG_ADPCM_EA_R2_DECODER 1
#define ENABLE_ADPCM_EA_R2_DECODER 1
#define CONFIG_ADPCM_EA_R3_DECODER 1
#define ENABLE_ADPCM_EA_R3_DECODER 1
#define CONFIG_ADPCM_EA_XAS_DECODER 1
#define ENABLE_ADPCM_EA_XAS_DECODER 1
#define CONFIG_ADPCM_G726_DECODER 1
#define ENABLE_ADPCM_G726_DECODER 1
#define CONFIG_ADPCM_IMA_AMV_DECODER 1
#define ENABLE_ADPCM_IMA_AMV_DECODER 1
#define CONFIG_ADPCM_IMA_DK3_DECODER 1
#define ENABLE_ADPCM_IMA_DK3_DECODER 1
#define CONFIG_ADPCM_IMA_DK4_DECODER 1
#define ENABLE_ADPCM_IMA_DK4_DECODER 1
#define CONFIG_ADPCM_IMA_EA_EACS_DECODER 1
#define ENABLE_ADPCM_IMA_EA_EACS_DECODER 1
#define CONFIG_ADPCM_IMA_EA_SEAD_DECODER 1
#define ENABLE_ADPCM_IMA_EA_SEAD_DECODER 1
#define CONFIG_ADPCM_IMA_QT_DECODER 1
#define ENABLE_ADPCM_IMA_QT_DECODER 1
#define CONFIG_ADPCM_IMA_SMJPEG_DECODER 1
#define ENABLE_ADPCM_IMA_SMJPEG_DECODER 1
#define CONFIG_ADPCM_IMA_WAV_DECODER 1
#define ENABLE_ADPCM_IMA_WAV_DECODER 1
#define CONFIG_ADPCM_IMA_WS_DECODER 1
#define ENABLE_ADPCM_IMA_WS_DECODER 1
#define CONFIG_ADPCM_MS_DECODER 1
#define ENABLE_ADPCM_MS_DECODER 1
#define CONFIG_ADPCM_SBPRO_2_DECODER 1
#define ENABLE_ADPCM_SBPRO_2_DECODER 1
#define CONFIG_ADPCM_SBPRO_3_DECODER 1
#define ENABLE_ADPCM_SBPRO_3_DECODER 1
#define CONFIG_ADPCM_SBPRO_4_DECODER 1
#define ENABLE_ADPCM_SBPRO_4_DECODER 1
#define CONFIG_ADPCM_SWF_DECODER 1
#define ENABLE_ADPCM_SWF_DECODER 1
#define CONFIG_ADPCM_THP_DECODER 1
#define ENABLE_ADPCM_THP_DECODER 1
#define CONFIG_ADPCM_XA_DECODER 1
#define ENABLE_ADPCM_XA_DECODER 1
#define CONFIG_ADPCM_YAMAHA_DECODER 1
#define ENABLE_ADPCM_YAMAHA_DECODER 1
#define CONFIG_DVBSUB_DECODER 1
#define ENABLE_DVBSUB_DECODER 1
#define CONFIG_DVDSUB_DECODER 1
#define ENABLE_DVDSUB_DECODER 1
#define ENABLE_LIBA52_DECODER 0
#define ENABLE_LIBAMR_NB_DECODER 0
#define ENABLE_LIBAMR_WB_DECODER 0
#define ENABLE_LIBDIRAC_DECODER 0
#define ENABLE_LIBFAAD_DECODER 0
#define ENABLE_LIBGSM_DECODER 0
#define ENABLE_LIBGSM_MS_DECODER 0
#define ENABLE_LIBSCHROEDINGER_DECODER 0
#define ENABLE_MPEG4AAC_DECODER 0
#define ENABLE_ASV1_ENCODER 0
#define ENABLE_ASV2_ENCODER 0
#define ENABLE_BMP_ENCODER 0
#define ENABLE_DNXHD_ENCODER 0
#define ENABLE_DVVIDEO_ENCODER 0
#define ENABLE_FFV1_ENCODER 0
#define ENABLE_FFVHUFF_ENCODER 0
#define ENABLE_FLASHSV_ENCODER 0
#define ENABLE_FLV_ENCODER 0
#define ENABLE_GIF_ENCODER 0
#define ENABLE_H261_ENCODER 0
#define ENABLE_H263_ENCODER 0
#define ENABLE_H263P_ENCODER 0
#define ENABLE_HUFFYUV_ENCODER 0
#define ENABLE_JPEGLS_ENCODER 0
#define ENABLE_LJPEG_ENCODER 0
#define ENABLE_MJPEG_ENCODER 0
#define CONFIG_MPEG1VIDEO_ENCODER 1
#define ENABLE_MPEG1VIDEO_ENCODER 1
#define ENABLE_MPEG2VIDEO_ENCODER 0
#define ENABLE_MPEG4_ENCODER 0
#define ENABLE_MSMPEG4V1_ENCODER 0
#define ENABLE_MSMPEG4V2_ENCODER 0
#define ENABLE_MSMPEG4V3_ENCODER 0
#define ENABLE_PAM_ENCODER 0
#define ENABLE_PBM_ENCODER 0
#define ENABLE_PGM_ENCODER 0
#define ENABLE_PGMYUV_ENCODER 0
#define ENABLE_PNG_ENCODER 0
#define ENABLE_PPM_ENCODER 0
#define ENABLE_QTRLE_ENCODER 0
#define ENABLE_RAWVIDEO_ENCODER 0
#define ENABLE_ROQ_ENCODER 0
#define ENABLE_RV10_ENCODER 0
#define ENABLE_RV20_ENCODER 0
#define ENABLE_SGI_ENCODER 0
#define CONFIG_SNOW_ENCODER 1
#define ENABLE_SNOW_ENCODER 1
#define ENABLE_SVQ1_ENCODER 0
#define ENABLE_TARGA_ENCODER 0
#define ENABLE_TIFF_ENCODER 0
#define ENABLE_WMV1_ENCODER 0
#define ENABLE_WMV2_ENCODER 0
#define ENABLE_ZLIB_ENCODER 0
#define ENABLE_ZMBV_ENCODER 0
#define ENABLE_AC3_ENCODER 0
#define ENABLE_FLAC_ENCODER 0
#define ENABLE_MP2_ENCODER 0
#define ENABLE_SONIC_ENCODER 0
#define ENABLE_SONIC_LS_ENCODER 0
#define ENABLE_VORBIS_ENCODER 0
#define ENABLE_WMAV1_ENCODER 0
#define ENABLE_WMAV2_ENCODER 0
#define ENABLE_PCM_ALAW_ENCODER 0
#define ENABLE_PCM_F32BE_ENCODER 0
#define ENABLE_PCM_MULAW_ENCODER 0
#define ENABLE_PCM_S8_ENCODER 0
#define ENABLE_PCM_S16BE_ENCODER 0
#define ENABLE_PCM_S16LE_ENCODER 0
#define ENABLE_PCM_S24BE_ENCODER 0
#define ENABLE_PCM_S24DAUD_ENCODER 0
#define ENABLE_PCM_S24LE_ENCODER 0
#define ENABLE_PCM_S32BE_ENCODER 0
#define ENABLE_PCM_S32LE_ENCODER 0
#define ENABLE_PCM_U8_ENCODER 0
#define ENABLE_PCM_U16BE_ENCODER 0
#define ENABLE_PCM_U16LE_ENCODER 0
#define ENABLE_PCM_U24BE_ENCODER 0
#define ENABLE_PCM_U24LE_ENCODER 0
#define ENABLE_PCM_U32BE_ENCODER 0
#define ENABLE_PCM_U32LE_ENCODER 0
#define ENABLE_PCM_ZORK_ENCODER 0
#define ENABLE_ROQ_DPCM_ENCODER 0
#define ENABLE_ADPCM_ADX_ENCODER 0
#define ENABLE_ADPCM_G726_ENCODER 0
#define ENABLE_ADPCM_IMA_QT_ENCODER 0
#define ENABLE_ADPCM_IMA_WAV_ENCODER 0
#define ENABLE_ADPCM_MS_ENCODER 0
#define ENABLE_ADPCM_SWF_ENCODER 0
#define ENABLE_ADPCM_YAMAHA_ENCODER 0
#define ENABLE_DVBSUB_ENCODER 0
#define ENABLE_DVDSUB_ENCODER 0
#define ENABLE_LIBAMR_NB_ENCODER 0
#define ENABLE_LIBAMR_WB_ENCODER 0
#define ENABLE_LIBDIRAC_ENCODER 0
#define ENABLE_LIBFAAC_ENCODER 0
#define ENABLE_LIBGSM_ENCODER 0
#define ENABLE_LIBGSM_MS_ENCODER 0
#define ENABLE_LIBMP3LAME_ENCODER 0
#define ENABLE_LIBSCHROEDINGER_ENCODER 0
#define ENABLE_LIBTHEORA_ENCODER 0
#define ENABLE_LIBVORBIS_ENCODER 0
#define ENABLE_LIBX264_ENCODER 0
#define ENABLE_LIBXVID_ENCODER 0
#define CONFIG_AAC_PARSER 1
#define ENABLE_AAC_PARSER 1
#define CONFIG_AC3_PARSER 1
#define ENABLE_AC3_PARSER 1
#define CONFIG_CAVSVIDEO_PARSER 1
#define ENABLE_CAVSVIDEO_PARSER 1
#define CONFIG_DCA_PARSER 1
#define ENABLE_DCA_PARSER 1
#define CONFIG_DIRAC_PARSER 1
#define ENABLE_DIRAC_PARSER 1
#define CONFIG_DVBSUB_PARSER 1
#define ENABLE_DVBSUB_PARSER 1
#define CONFIG_DVDSUB_PARSER 1
#define ENABLE_DVDSUB_PARSER 1
#define CONFIG_H261_PARSER 1
#define ENABLE_H261_PARSER 1
#define CONFIG_H263_PARSER 1
#define ENABLE_H263_PARSER 1
#define CONFIG_H264_PARSER 1
#define ENABLE_H264_PARSER 1
#define CONFIG_MJPEG_PARSER 1
#define ENABLE_MJPEG_PARSER 1
#define CONFIG_MLP_PARSER 1
#define ENABLE_MLP_PARSER 1
#define CONFIG_MPEG4VIDEO_PARSER 1
#define ENABLE_MPEG4VIDEO_PARSER 1
#define CONFIG_MPEGAUDIO_PARSER 1
#define ENABLE_MPEGAUDIO_PARSER 1
#define CONFIG_MPEGVIDEO_PARSER 1
#define ENABLE_MPEGVIDEO_PARSER 1
#define CONFIG_PNM_PARSER 1
#define ENABLE_PNM_PARSER 1
#define CONFIG_VC1_PARSER 1
#define ENABLE_VC1_PARSER 1
#define CONFIG_VP3_PARSER 1
#define ENABLE_VP3_PARSER 1
#define CONFIG_AAC_DEMUXER 1
#define ENABLE_AAC_DEMUXER 1
#define CONFIG_AC3_DEMUXER 1
#define ENABLE_AC3_DEMUXER 1
#define CONFIG_AIFF_DEMUXER 1
#define ENABLE_AIFF_DEMUXER 1
#define CONFIG_AMR_DEMUXER 1
#define ENABLE_AMR_DEMUXER 1
#define CONFIG_APC_DEMUXER 1
#define ENABLE_APC_DEMUXER 1
#define CONFIG_APE_DEMUXER 1
#define ENABLE_APE_DEMUXER 1
#define CONFIG_ASF_DEMUXER 1
#define ENABLE_ASF_DEMUXER 1
#define CONFIG_AU_DEMUXER 1
#define ENABLE_AU_DEMUXER 1
#define CONFIG_AVI_DEMUXER 1
#define ENABLE_AVI_DEMUXER 1
#define ENABLE_AVISYNTH_DEMUXER 0
#define CONFIG_AVS_DEMUXER 1
#define ENABLE_AVS_DEMUXER 1
#define CONFIG_BETHSOFTVID_DEMUXER 1
#define ENABLE_BETHSOFTVID_DEMUXER 1
#define CONFIG_BFI_DEMUXER 1
#define ENABLE_BFI_DEMUXER 1
#define CONFIG_C93_DEMUXER 1
#define ENABLE_C93_DEMUXER 1
#define CONFIG_DAUD_DEMUXER 1
#define ENABLE_DAUD_DEMUXER 1
#define CONFIG_DIRAC_DEMUXER 1
#define ENABLE_DIRAC_DEMUXER 1
#define CONFIG_DSICIN_DEMUXER 1
#define ENABLE_DSICIN_DEMUXER 1
#define CONFIG_DTS_DEMUXER 1
#define ENABLE_DTS_DEMUXER 1
#define CONFIG_DV_DEMUXER 1
#define ENABLE_DV_DEMUXER 1
#define CONFIG_DXA_DEMUXER 1
#define ENABLE_DXA_DEMUXER 1
#define CONFIG_EA_DEMUXER 1
#define ENABLE_EA_DEMUXER 1
#define CONFIG_EA_CDATA_DEMUXER 1
#define ENABLE_EA_CDATA_DEMUXER 1
#define CONFIG_FFM_DEMUXER 1
#define ENABLE_FFM_DEMUXER 1
#define CONFIG_FLAC_DEMUXER 1
#define ENABLE_FLAC_DEMUXER 1
#define CONFIG_FLIC_DEMUXER 1
#define ENABLE_FLIC_DEMUXER 1
#define CONFIG_FLV_DEMUXER 1
#define ENABLE_FLV_DEMUXER 1
#define CONFIG_FOURXM_DEMUXER 1
#define ENABLE_FOURXM_DEMUXER 1
#define CONFIG_GSM_DEMUXER 1
#define ENABLE_GSM_DEMUXER 1
#define CONFIG_GXF_DEMUXER 1
#define ENABLE_GXF_DEMUXER 1
#define CONFIG_H261_DEMUXER 1
#define ENABLE_H261_DEMUXER 1
#define CONFIG_H263_DEMUXER 1
#define ENABLE_H263_DEMUXER 1
#define CONFIG_H264_DEMUXER 1
#define ENABLE_H264_DEMUXER 1
#define CONFIG_IDCIN_DEMUXER 1
#define ENABLE_IDCIN_DEMUXER 1
#define CONFIG_IFF_DEMUXER 1
#define ENABLE_IFF_DEMUXER 1
#define CONFIG_IMAGE2_DEMUXER 1
#define ENABLE_IMAGE2_DEMUXER 1
#define CONFIG_IMAGE2PIPE_DEMUXER 1
#define ENABLE_IMAGE2PIPE_DEMUXER 1
#define CONFIG_INGENIENT_DEMUXER 1
#define ENABLE_INGENIENT_DEMUXER 1
#define CONFIG_IPMOVIE_DEMUXER 1
#define ENABLE_IPMOVIE_DEMUXER 1
#define CONFIG_LMLM4_DEMUXER 1
#define ENABLE_LMLM4_DEMUXER 1
#define CONFIG_M4V_DEMUXER 1
#define ENABLE_M4V_DEMUXER 1
#define CONFIG_MATROSKA_DEMUXER 1
#define ENABLE_MATROSKA_DEMUXER 1
#define CONFIG_MJPEG_DEMUXER 1
#define ENABLE_MJPEG_DEMUXER 1
#define CONFIG_MLP_DEMUXER 1
#define ENABLE_MLP_DEMUXER 1
#define CONFIG_MM_DEMUXER 1
#define ENABLE_MM_DEMUXER 1
#define CONFIG_MMF_DEMUXER 1
#define ENABLE_MMF_DEMUXER 1
#define CONFIG_MOV_DEMUXER 1
#define ENABLE_MOV_DEMUXER 1
#define CONFIG_MP3_DEMUXER 1
#define ENABLE_MP3_DEMUXER 1
#define CONFIG_MPC_DEMUXER 1
#define ENABLE_MPC_DEMUXER 1
#define CONFIG_MPC8_DEMUXER 1
#define ENABLE_MPC8_DEMUXER 1
#define CONFIG_MPEGPS_DEMUXER 1
#define ENABLE_MPEGPS_DEMUXER 1
#define CONFIG_MPEGTS_DEMUXER 1
#define ENABLE_MPEGTS_DEMUXER 1
#define CONFIG_MPEGTSRAW_DEMUXER 1
#define ENABLE_MPEGTSRAW_DEMUXER 1
#define CONFIG_MPEGVIDEO_DEMUXER 1
#define ENABLE_MPEGVIDEO_DEMUXER 1
#define CONFIG_MSNWC_TCP_DEMUXER 1
#define ENABLE_MSNWC_TCP_DEMUXER 1
#define CONFIG_MTV_DEMUXER 1
#define ENABLE_MTV_DEMUXER 1
#define CONFIG_MVI_DEMUXER 1
#define ENABLE_MVI_DEMUXER 1
#define CONFIG_MXF_DEMUXER 1
#define ENABLE_MXF_DEMUXER 1
#define CONFIG_NSV_DEMUXER 1
#define ENABLE_NSV_DEMUXER 1
#define CONFIG_NUT_DEMUXER 1
#define ENABLE_NUT_DEMUXER 1
#define CONFIG_NUV_DEMUXER 1
#define ENABLE_NUV_DEMUXER 1
#define CONFIG_OGG_DEMUXER 1
#define ENABLE_OGG_DEMUXER 1
#define CONFIG_OMA_DEMUXER 1
#define ENABLE_OMA_DEMUXER 1
#define CONFIG_PCM_ALAW_DEMUXER 1
#define ENABLE_PCM_ALAW_DEMUXER 1
#define CONFIG_PCM_MULAW_DEMUXER 1
#define ENABLE_PCM_MULAW_DEMUXER 1
#define CONFIG_PCM_S16BE_DEMUXER 1
#define ENABLE_PCM_S16BE_DEMUXER 1
#define CONFIG_PCM_S16LE_DEMUXER 1
#define ENABLE_PCM_S16LE_DEMUXER 1
#define CONFIG_PCM_S8_DEMUXER 1
#define ENABLE_PCM_S8_DEMUXER 1
#define CONFIG_PCM_U16BE_DEMUXER 1
#define ENABLE_PCM_U16BE_DEMUXER 1
#define CONFIG_PCM_U16LE_DEMUXER 1
#define ENABLE_PCM_U16LE_DEMUXER 1
#define CONFIG_PCM_U8_DEMUXER 1
#define ENABLE_PCM_U8_DEMUXER 1
#define CONFIG_PVA_DEMUXER 1
#define ENABLE_PVA_DEMUXER 1
#define CONFIG_RAWVIDEO_DEMUXER 1
#define ENABLE_RAWVIDEO_DEMUXER 1
#define ENABLE_REDIR_DEMUXER 0
#define CONFIG_RL2_DEMUXER 1
#define ENABLE_RL2_DEMUXER 1
#define CONFIG_RM_DEMUXER 1
#define ENABLE_RM_DEMUXER 1
#define CONFIG_ROQ_DEMUXER 1
#define ENABLE_ROQ_DEMUXER 1
#define CONFIG_RPL_DEMUXER 1
#define ENABLE_RPL_DEMUXER 1
#define ENABLE_RTSP_DEMUXER 0
#define ENABLE_SDP_DEMUXER 0
#define CONFIG_SEGAFILM_DEMUXER 1
#define ENABLE_SEGAFILM_DEMUXER 1
#define CONFIG_SHORTEN_DEMUXER 1
#define ENABLE_SHORTEN_DEMUXER 1
#define CONFIG_SIFF_DEMUXER 1
#define ENABLE_SIFF_DEMUXER 1
#define CONFIG_SMACKER_DEMUXER 1
#define ENABLE_SMACKER_DEMUXER 1
#define CONFIG_SOL_DEMUXER 1
#define ENABLE_SOL_DEMUXER 1
#define CONFIG_STR_DEMUXER 1
#define ENABLE_STR_DEMUXER 1
#define CONFIG_SWF_DEMUXER 1
#define ENABLE_SWF_DEMUXER 1
#define CONFIG_THP_DEMUXER 1
#define ENABLE_THP_DEMUXER 1
#define CONFIG_TIERTEXSEQ_DEMUXER 1
#define ENABLE_TIERTEXSEQ_DEMUXER 1
#define CONFIG_TTA_DEMUXER 1
#define ENABLE_TTA_DEMUXER 1
#define CONFIG_TXD_DEMUXER 1
#define ENABLE_TXD_DEMUXER 1
#define CONFIG_VC1_DEMUXER 1
#define ENABLE_VC1_DEMUXER 1
#define CONFIG_VC1T_DEMUXER 1
#define ENABLE_VC1T_DEMUXER 1
#define CONFIG_VMD_DEMUXER 1
#define ENABLE_VMD_DEMUXER 1
#define CONFIG_VOC_DEMUXER 1
#define ENABLE_VOC_DEMUXER 1
#define CONFIG_WAV_DEMUXER 1
#define ENABLE_WAV_DEMUXER 1
#define CONFIG_WC3_DEMUXER 1
#define ENABLE_WC3_DEMUXER 1
#define CONFIG_WSAUD_DEMUXER 1
#define ENABLE_WSAUD_DEMUXER 1
#define CONFIG_WSVQA_DEMUXER 1
#define ENABLE_WSVQA_DEMUXER 1
#define CONFIG_WV_DEMUXER 1
#define ENABLE_WV_DEMUXER 1
#define CONFIG_XA_DEMUXER 1
#define ENABLE_XA_DEMUXER 1
#define CONFIG_YUV4MPEGPIPE_DEMUXER 1
#define ENABLE_YUV4MPEGPIPE_DEMUXER 1
#define ENABLE_LIBNUT_DEMUXER 0
#define ENABLE_AC3_MUXER 0
#define ENABLE_ADTS_MUXER 0
#define ENABLE_AIFF_MUXER 0
#define ENABLE_AMR_MUXER 0
#define ENABLE_ASF_MUXER 0
#define ENABLE_ASF_STREAM_MUXER 0
#define ENABLE_AU_MUXER 0
#define ENABLE_AVI_MUXER 0
#define ENABLE_AVM2_MUXER 0
#define ENABLE_CRC_MUXER 0
#define ENABLE_DAUD_MUXER 0
#define ENABLE_DIRAC_MUXER 0
#define ENABLE_DTS_MUXER 0
#define ENABLE_DV_MUXER 0
#define ENABLE_FFM_MUXER 0
#define ENABLE_FLAC_MUXER 0
#define ENABLE_FLV_MUXER 0
#define ENABLE_FRAMECRC_MUXER 0
#define ENABLE_GIF_MUXER 0
#define ENABLE_GXF_MUXER 0
#define ENABLE_H261_MUXER 0
#define ENABLE_H263_MUXER 0
#define ENABLE_H264_MUXER 0
#define ENABLE_IMAGE2_MUXER 0
#define ENABLE_IMAGE2PIPE_MUXER 0
#define ENABLE_IPOD_MUXER 0
#define ENABLE_M4V_MUXER 0
#define ENABLE_MATROSKA_MUXER 0
#define ENABLE_MATROSKA_AUDIO_MUXER 0
#define ENABLE_MJPEG_MUXER 0
#define ENABLE_MMF_MUXER 0
#define ENABLE_MOV_MUXER 0
#define ENABLE_MP2_MUXER 0
#define ENABLE_MP3_MUXER 0
#define ENABLE_MP4_MUXER 0
#define ENABLE_MPEG1SYSTEM_MUXER 0
#define ENABLE_MPEG1VCD_MUXER 0
#define ENABLE_MPEG1VIDEO_MUXER 0
#define ENABLE_MPEG2DVD_MUXER 0
#define ENABLE_MPEG2SVCD_MUXER 0
#define ENABLE_MPEG2VIDEO_MUXER 0
#define ENABLE_MPEG2VOB_MUXER 0
#define ENABLE_MPEGTS_MUXER 0
#define ENABLE_MPJPEG_MUXER 0
#define ENABLE_NULL_MUXER 0
#define ENABLE_NUT_MUXER 0
#define ENABLE_OGG_MUXER 0
#define ENABLE_PCM_ALAW_MUXER 0
#define ENABLE_PCM_MULAW_MUXER 0
#define ENABLE_PCM_S16BE_MUXER 0
#define ENABLE_PCM_S16LE_MUXER 0
#define ENABLE_PCM_S8_MUXER 0
#define ENABLE_PCM_U16BE_MUXER 0
#define ENABLE_PCM_U16LE_MUXER 0
#define ENABLE_PCM_U8_MUXER 0
#define ENABLE_PSP_MUXER 0
#define ENABLE_RAWVIDEO_MUXER 0
#define ENABLE_RM_MUXER 0
#define ENABLE_ROQ_MUXER 0
#define ENABLE_RTP_MUXER 0
#define ENABLE_SWF_MUXER 0
#define ENABLE_TG2_MUXER 0
#define ENABLE_TGP_MUXER 0
#define ENABLE_VC1T_MUXER 0
#define ENABLE_VOC_MUXER 0
#define ENABLE_WAV_MUXER 0
#define ENABLE_YUV4MPEGPIPE_MUXER 0
#define ENABLE_LIBNUT_MUXER 0
#define ENABLE_FILE_PROTOCOL 0
#define ENABLE_HTTP_PROTOCOL 0
#define ENABLE_PIPE_PROTOCOL 0
#define ENABLE_RTP_PROTOCOL 0
#define ENABLE_TCP_PROTOCOL 0
#define ENABLE_UDP_PROTOCOL 0
#define CONFIG_DUMP_EXTRADATA_BSF 1
#define ENABLE_DUMP_EXTRADATA_BSF 1
#define CONFIG_H264_MP4TOANNEXB_BSF 1
#define ENABLE_H264_MP4TOANNEXB_BSF 1
#define CONFIG_IMX_DUMP_HEADER_BSF 1
#define ENABLE_IMX_DUMP_HEADER_BSF 1
#define CONFIG_MJPEGA_DUMP_HEADER_BSF 1
#define ENABLE_MJPEGA_DUMP_HEADER_BSF 1
#define CONFIG_MP3_HEADER_COMPRESS_BSF 1
#define ENABLE_MP3_HEADER_COMPRESS_BSF 1
#define CONFIG_MP3_HEADER_DECOMPRESS_BSF 1
#define ENABLE_MP3_HEADER_DECOMPRESS_BSF 1
#define CONFIG_MOV2TEXTSUB_BSF 1
#define ENABLE_MOV2TEXTSUB_BSF 1
#define CONFIG_NOISE_BSF 1
#define ENABLE_NOISE_BSF 1
#define CONFIG_REMOVE_EXTRADATA_BSF 1
#define ENABLE_REMOVE_EXTRADATA_BSF 1
#define CONFIG_TEXT2MOVSUB_BSF 1
#define ENABLE_TEXT2MOVSUB_BSF 1

#undef CONFIG_LIBDIRAC
#undef CONFIG_LIBFAAC

#undef CONFIG_LIBSCHROEDINGER
#undef CONFIG_LIBX264
#undef CONFIG_LIBXVID

/* Use codec libs included in mplayer CVS / source dist: */
#define CONFIG_MP3LIB 1
#define CONFIG_LIBA52 1
#define CONFIG_LIBMPEG2 1

/* XAnim DLL support */
#undef CONFIG_XANIM
/* Default search path */
#undef XACODEC_PATH

/* RealPlayer DLL support */
#undef CONFIG_REALCODECS
/* Default search path */
#undef REALCODEC_PATH

/* LIVE555 Streaming Media library support */
#undef CONFIG_LIVE555

/* libnemesi Streaming Media library support */
#undef CONFIG_LIBNEMESI

/* Use 3dnow/mmxext/sse/mmx optimized fast memcpy() [maybe buggy... signal 4]*/
#undef CONFIG_FASTMEMCPY

/* Use UnRAR executable for Vobsubs */
#undef CONFIG_UNRAR_EXEC

/* gui support, please do not edit this option */
#undef CONFIG_GUI
#undef CONFIG_GTK2

/* Audio output drivers */
#undef CONFIG_OSS_AUDIO
#define PATH_DEV_DSP ""
#define PATH_DEV_MIXER ""
#undef CONFIG_ALSA
#undef CONFIG_ALSA5
#undef CONFIG_ALSA9
#undef CONFIG_ALSA1X

#undef CONFIG_ESD
#undef CONFIG_ESD_LATENCY
#undef CONFIG_PULSE



#undef HAVE_SYS_ASOUNDLIB_H
#undef HAVE_ALSA_ASOUNDLIB_H
#undef CONFIG_SUN_AUDIO


#undef CONFIG_NAS

/* Enable fast OSD/SUB renderer (looks ugly, but uses less CPU power) */
#undef FAST_OSD
#undef FAST_OSD_TABLE

/* Enable TV Interface support */
#undef CONFIG_TV

/* Enable Video 4 Linux TV interface support */
#undef CONFIG_TV_V4L

/* Enable Video 4 Linux 1 TV interface support */


/* Enable Video 4 Linux 2 TV interface support */
#undef CONFIG_TV_V4L2

/* Enable DirectShow TV interface support */
#undef CONFIG_TV_DSHOW

/* *BSD BrookTree headers */



/* Enable *BSD BrookTree TV interface support */


/* Enable TV Teletext Interface support */
#undef CONFIG_TV_TELETEXT

/* Enable Radio Interface support */
#undef CONFIG_RADIO

/* Enable Capture for Radio Interface support */
#undef CONFIG_RADIO_CAPTURE

/* Enable Video 4 Linux Radio interface support */
#undef CONFIG_RADIO_V4L

/* Enable Video 4 Linux 2 Radio interface support */
#undef CONFIG_RADIO_V4L2

/* Enable *BSD BrookTree Radio interface support */
#undef CONFIG_RADIO_BSDBT848

/* Enable Video 4 Linux 2 MPEG PVR support */
#undef CONFIG_PVR

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
#define WORDS_BIGENDIAN 1

/* Define if your processor can access unaligned data in a fast way */


#define ENABLE_X86 0
#define ENABLE_X86_32 0
#define ENABLE_X86_64 0
#define ENABLE_IA64 0
#define ENABLE_SPARC 0
#define ENABLE_ARM 0
#define ENABLE_ARMV4L 0
#define ENABLE_SH 0
#define ARCH_POWERPC 1
#define ENABLE_POWERPC 1
#define ARCH_PPC 1
#define ENABLE_PPC 1
#define ENABLE_ALPHA 0
#define ENABLE_SGI_MIPS 0
#define ENABLE_PA_RISC 0
#define ENABLE_S390 0
#define ENABLE_S390X 0
#define ENABLE_VAX 0
#define ENABLE_BFIN 0
#define ENABLE_XTENSA 0
#define ENABLE_GENERIC 0

/* For the PPC.  G5 has the dcbzl when in 64bit mode but G4s and earlier do not
   have the instruction. */
#undef HAVE_DCBZL

/* Define this for Cygwin build for win32 */


/* Define this to any prefered value from 386 up to infinity with step 100 */
#define __CPU__ ppc

#undef MP_WORDSIZE

#undef CONFIG_VCD

#ifdef sun
#define	DEFAULT_CDROM_DEVICE	"/vol/dev/aliases/cdrom0"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#elif defined(WIN32) || defined(__OS2__)
#define DEFAULT_CDROM_DEVICE    "D:"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#elif defined(__APPLE__) || defined(__DARWIN__)
#define DEFAULT_CDROM_DEVICE    "/dev/disk1"
#define DEFAULT_DVD_DEVICE	"/dev/rdiskN"
#elif defined(__OpenBSD__)
#define DEFAULT_CDROM_DEVICE	"/dev/rcd0a"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#elif defined(__FreeBSD__) || defined(__FreeBSD_kernel__)
#define DEFAULT_CDROM_DEVICE	"/dev/acd0"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#elif defined(__DragonFly__)
#define DEFAULT_CDROM_DEVICE	"/dev/cd0"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#elif defined(__AMIGAOS4__)
#define DEFAULT_CDROM_DEVICE    "a1ide.device:2"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#elif defined(GEKKO)
#define DEFAULT_CDROM_DEVICE    "/dev/di"
#define DEFAULT_DVD_DEVICE     "/dev/di"
#else
#define DEFAULT_CDROM_DEVICE    "/dev/cdrom"
#define DEFAULT_DVD_DEVICE	"/dev/dvd"
#endif


/*----------------------------------------------------------------------------
**
** NOTE: Instead of modifying these definitions here, use the
**       --enable/--disable options of the ./configure script!
**       See ./configure --help for details.
**
*---------------------------------------------------------------------------*/

/* C99 *lrint* and round* functions available */
#undef HAVE_LLRINT
#define HAVE_LRINT 1
#define HAVE_LRINTF 1
#define HAVE_ROUND 1
#define HAVE_ROUNDF 1

/* mkstemp support */
#define HAVE_MKSTEMP 1

/* nanosleep support */
#undef HAVE_NANOSLEEP

/* SMB support */
#undef CONFIG_LIBSMBCLIENT

/* termcap flag for getch2.c */
#undef HAVE_TERMCAP

/* termios flag for getch2.c */
#undef HAVE_TERMIOS
#undef HAVE_TERMIOS_H
#undef HAVE_SYS_TERMIOS_H

/* enable PNG support */
#undef CONFIG_PNG

/* enable JPEG support */
#undef CONFIG_JPEG

/* enable PNM support */
#undef CONFIG_PNM

/* enable md5sum support */
#undef CONFIG_MD5SUM

/* enable yuv4mpeg support */
#undef CONFIG_YUV4MPEG

/* enable GIF support */
#undef CONFIG_GIF
#undef CONFIG_GIF_4


/* enable bitmap font support */
#define CONFIG_BITMAP_FONT 1

/* enable FreeType support */
#undef CONFIG_FREETYPE

/* enable Fontconfig support */
#undef CONFIG_FONTCONFIG

/* enable SSA/ASS support */
#undef CONFIG_ASS

/* enable FriBiDi usage */
#undef CONFIG_FRIBIDI

/* enable ENCA usage */
#undef CONFIG_ENCA

/* liblzo support */
#undef CONFIG_LIBLZO

/* libmad support */
#undef CONFIG_LIBMAD

/* enable OggVorbis support */
#define CONFIG_OGGVORBIS 1
#define CONFIG_TREMOR 1

/* enable Speex support */
#undef CONFIG_SPEEX

/* enable musepack support */
#undef CONFIG_MUSEPACK

/* enable OggTheora support */
#undef CONFIG_OGGTHEORA

/* enable FAAD (AAC) support */
#define CONFIG_FAAD 1
#define CONFIG_FAAD_INTERNAL 1

/* enable FAAC (AAC encoder) support */
#undef CONFIG_FAAC

/* enable libdca support */
#undef CONFIG_LIBDCA

/* enable LADSPA plugin support */
#undef CONFIG_LADSPA

/* enable network */
#define CONFIG_NETWORK 1

/* enable ftp support */
#define CONFIG_FTP 1

/* enable vstream support */
#undef CONFIG_VSTREAM

/* enable winsock2 instead of Unix functions*/
#undef HAVE_WINSOCK2

/* define this to use inet_aton() instead of inet_pton() */
//#undef HAVE_ATON
#define HAVE_ATON 1

/* socklen_t support */
#ifndef CODECS2HTML
#undef HAVE_SOCKLEN_T
#ifndef HAVE_SOCKLEN_T
#define HAVE_SOCKLEN_T 1
typedef int socklen_t;
#endif
#endif

/* enables / disables cdparanoia support */
#undef CONFIG_CDDA
#undef CONFIG_CDDB

/* enables / disables VIDIX usage */
#undef CONFIG_VIDIX
#undef CONFIG_VIDIX_DRV_CYBERBLADE
#undef CONFIG_VIDIX_DRV_IVTV
#undef CONFIG_VIDIX_DRV_MACH64
#undef CONFIG_VIDIX_DRV_MGA
#undef CONFIG_VIDIX_DRV_MGA_CRTC2
#undef CONFIG_VIDIX_DRV_NVIDIA
#undef CONFIG_VIDIX_DRV_PM3
#undef CONFIG_VIDIX_DRV_RADEON
#undef CONFIG_VIDIX_DRV_RAGE128
#undef CONFIG_VIDIX_DRV_S3
#undef CONFIG_VIDIX_DRV_SIS
#undef CONFIG_VIDIX_DRV_UNICHROME


/* enables / disables new input joystick support */
#undef CONFIG_JOYSTICK

/* enables / disables QTX codecs */
#undef CONFIG_QTX_CODECS
#undef CONFIG_QTX_CODECS_WIN32

/* enables / disables osd menu */
#define CONFIG_MENU 1

/* enables / disables subtitles sorting */
#define CONFIG_SORTSUB 1

/* XMMS input plugin support */
#undef CONFIG_XMMS
#define XMMS_INPUT_PLUGIN_DIR ""

/* enables inet6 support */
#undef HAVE_AF_INET6

/* do we have gethostbyname2? */
#undef HAVE_GETHOSTBYNAME2

/* Extension defines */
#define ENABLE_ALTIVEC 0
#define ENABLE_MMX 0
#define ENABLE_MMX2 0
#define ENABLE_3DNOW 0
#define ENABLE_3DNOWEX 0
#define ENABLE_SSE 0
#define ENABLE_SSE2 0
#define ENABLE_SSSE3 0
#define ENABLE_FAST_CMOV 0
#define ENABLE_CMOV 0
#define ENABLE_ARMV5TE 0
#define ENABLE_ARMV6 0
#define ENABLE_IWMMXT 0
#define ENABLE_MLIB 0
#define ENABLE_MMI 0
#define ENABLE_SH4 0
#define ENABLE_VIS 0
#define ENABLE_MVI 0

	// enables usage of altivec.h

/* libvo options */
#define SCREEN_SIZE_X 1
#define SCREEN_SIZE_Y 1
#undef CONFIG_X11
#undef CONFIG_XV
#undef HAVE_XVMC
#undef CONFIG_XF86VM
#undef CONFIG_XF86XK
#undef CONFIG_XINERAMA
#undef CONFIG_GL
#undef GL_WIN32
#undef CONFIG_DGA
#undef CONFIG_DGA1
#undef CONFIG_DGA2
#undef CONFIG_SDL
/* defined for SDLlib with keyrepeat bugs (before 1.2.1) */


#undef CONFIG_GGI
#undef CONFIG_GGIWMH
#undef CONFIG_3DFX
#undef CONFIG_S3FB
#undef CONFIG_WII
#undef CONFIG_TDFXFB
#undef CONFIG_XVR100

#undef CONFIG_DIRECTFB

#undef CONFIG_DFBMGA
#undef CONFIG_ZR
#undef CONFIG_BL
#undef CONFIG_MGA
#undef CONFIG_XMGA
#undef CONFIG_FBDEV
#undef CONFIG_DXR2
#undef CONFIG_DXR3
#undef CONFIG_IVTV
#undef CONFIG_V4L2_DECODER
#undef CONFIG_DVB
#undef CONFIG_DVB_HEAD
#undef CONFIG_DVBIN 
#undef CONFIG_SVGALIB
#undef CONFIG_VESA
#undef CONFIG_XSS
#undef CONFIG_XDPMS
#undef CONFIG_AA
#undef CONFIG_CACA
#undef CONFIG_TGA
#undef CONFIG_TOOLAME
#undef CONFIG_TWOLAME

/* used by GUI: */


#if defined(CONFIG_GL) || defined(CONFIG_X11) || defined(CONFIG_XV)
#define X11_FULLSCREEN 1
#endif

#endif /* MPLAYER_CONFIG_H */
